# Generated by Django 5.0.2 on 2024-03-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_plotting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plotting', to=settings.AUTH_USER_MODEL),
        ),
    ]
