# Generated by Django 4.2.7 on 2024-03-04 15:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_plotting_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotting',
            name='plot',
            field=models.ImageField(blank=True, upload_to=app.models.upload_path),
        ),
    ]
